# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-28 11:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='authenticated_users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('contact_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='authoritylist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorityperson', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='hostellist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostelname', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='authenticated_users',
            name='authority_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleaningdetails.authoritylist'),
        ),
        migrations.AddField(
            model_name='authenticated_users',
            name='hostel_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleaningdetails.hostellist'),
        ),
    ]
