# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-28 11:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleaningdetails', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authenticated_users',
            old_name='authority_person',
            new_name='authority_status',
        ),
        migrations.RenameField(
            model_name='authoritylist',
            old_name='authorityperson',
            new_name='authorityststus',
        ),
    ]
