# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-28 11:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleaningdetails', '0002_auto_20170928_1120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authenticated_users',
            old_name='password',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='authenticated_users',
            name='contact_no',
        ),
        migrations.RemoveField(
            model_name='authenticated_users',
            name='username',
        ),
    ]
