# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-28 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cleaningdetails', '0003_auto_20170928_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='accesslevels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='total_authenticated_users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('webmail_id', models.CharField(max_length=200)),
                ('access_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleaningdetails.accesslevels')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleaningdetails.authoritylist')),
                ('hostel_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleaningdetails.hostellist')),
            ],
        ),
        migrations.RemoveField(
            model_name='authenticated_users',
            name='authority_status',
        ),
        migrations.RemoveField(
            model_name='authenticated_users',
            name='hostel_name',
        ),
        migrations.DeleteModel(
            name='authenticated_users',
        ),
    ]
