# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-28 12:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleaningdetails', '0004_auto_20170928_1215'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='authoritylist',
            new_name='designations',
        ),
        migrations.RenameField(
            model_name='designations',
            old_name='authorityststus',
            new_name='authoritystatus',
        ),
    ]
