# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-28 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaningdetails', '0005_auto_20170928_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='total_authenticated_users',
            name='webmail_id',
            field=models.EmailField(max_length=254),
        ),
    ]
