# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-28 12:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cleaningdetails', '0007_dhansiri_authorities_dibang_authorities_dihing_authorities_kapili_authorities_lohit_authorities_mana'),
    ]

    operations = [
        migrations.CreateModel(
            name='brahmputra_authorities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('webmail_id', models.EmailField(max_length=254)),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleaningdetails.designations')),
            ],
        ),
    ]
