# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-28 12:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleaningdetails', '0008_brahmputra_authorities'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='brahmputra_authorities',
            unique_together=set([('name', 'designation')]),
        ),
        migrations.AlterUniqueTogether(
            name='dhansiri_authorities',
            unique_together=set([('name', 'designation')]),
        ),
        migrations.AlterUniqueTogether(
            name='dibang_authorities',
            unique_together=set([('name', 'designation')]),
        ),
        migrations.AlterUniqueTogether(
            name='dihing_authorities',
            unique_together=set([('name', 'designation')]),
        ),
        migrations.AlterUniqueTogether(
            name='kapili_authorities',
            unique_together=set([('name', 'designation')]),
        ),
        migrations.AlterUniqueTogether(
            name='lohit_authorities',
            unique_together=set([('name', 'designation')]),
        ),
        migrations.AlterUniqueTogether(
            name='manas_authorities',
            unique_together=set([('name', 'designation')]),
        ),
        migrations.AlterUniqueTogether(
            name='siang_authorities',
            unique_together=set([('name', 'designation')]),
        ),
        migrations.AlterUniqueTogether(
            name='subansiri_authorities',
            unique_together=set([('name', 'designation')]),
        ),
        migrations.AlterUniqueTogether(
            name='total_authenticated_users',
            unique_together=set([('hostel_name', 'name', 'designation')]),
        ),
    ]
